from sqlalchemy import BigInteger, Boolean, Column, ForeignKey, Integer, String, Date, Float
from sqlalchemy.orm import relationship

from database import Base


class Loan(Base):
    __tablename__ = "loan"

    LoanNumber = Column(BigInteger, primary_key=True, index=True)
    DateApproved = Column(Date)
    SBAOfficeCode = Column(String)
    ProcessingMethod = Column(String)
    BorrowerName = Column(String)
    BorrowerAddress = Column(String)
    BorrowerCity = Column(String)
    BorrowerState = Column(String)
    BorrowerZip = Column(String)
    LoanStatusDate = Column(Date)
    LoanStatus = Column(String)
    Term = Column(Integer)
    SBAGuarantyPercentage = Column(Float)
    InitialApprovalAmount = Column(Float)
    CurrentApprovalAmount = Column(Float)
    UndisbursedAmount = Column(Float)
    FranchiseName = Column(String)
    ServicingLenderLocationID = Column(String)
    ServicingLenderName = Column(String)
    ServicingLenderAddress = Column(String)
    ServicingLenderCity = Column(String)
    ServicingLenderState = Column(String)
    ServicingLenderZip = Column(String)
    RuralUrbanIndicator = Column(String)
    HubzoneIndicator = Column(String)
    LMIIndicator = Column(String)
    BusinessAgeDescription = Column(String)
    ProjectCity = Column(String)
    ProjectCountyName = Column(String)
    ProjectState = Column(String)
    ProjectZip = Column(String)
    CD = Column(String)
    JobsReported = Column(Integer)
    NAICSCode = Column(String)
    Race = Column(String)
    Ethnicity = Column(String)
    UTILITIES_PROCEED = Column(Float)
    PAYROLL_PROCEED = Column(Float)
    MORTGAGE_INTEREST_PROCEED = Column(Float)
    RENT_PROCEED = Column(Float)
    REFINANCE_EIDL_PROCEED = Column(Float)
    HEALTH_CARE_PROCEED = Column(Float)
    DEBT_INTEREST_PROCEED = Column(Float)
    BusinessType = Column(String)
    OriginatingLenderLocationID = Column(String)
    OriginatingLender = Column(String)
    OriginatingLenderCity = Column(String)
    OriginatingLenderState = Column(String)
    Gender = Column(String)
    Veteran = Column(String)
    NonProfit = Column(String)
    ForgivenessAmount = Column(Float)
    ForgivenessDate = Column(Date)
