from pydantic import BaseModel
from typing import Optional
from datetime import date

class Loan(BaseModel):
    LoanNumber: str  # Mandatory field
    DateApproved: Optional[date]
    SBAOfficeCode: Optional[str]
    ProcessingMethod: Optional[str]
    BorrowerName: Optional[str]
    BorrowerAddress: Optional[str]
    BorrowerCity: Optional[str]
    BorrowerState: Optional[str]
    BorrowerZip: Optional[str]
    LoanStatusDate: Optional[date]
    LoanStatus: Optional[str]
    Term: Optional[int]
    SBAGuarantyPercentage: Optional[float]
    InitialApprovalAmount: Optional[float]
    CurrentApprovalAmount: Optional[float]
    UndisbursedAmount: Optional[float]
    FranchiseName: Optional[str]
    ServicingLenderLocationID: Optional[str]
    ServicingLenderName: Optional[str]
    ServicingLenderAddress: Optional[str]
    ServicingLenderCity: Optional[str]
    ServicingLenderState: Optional[str]
    ServicingLenderZip: Optional[str]
    RuralUrbanIndicator: Optional[str]
    HubzoneIndicator: Optional[str]
    LMIIndicator: Optional[str]
    BusinessAgeDescription: Optional[str]
    ProjectCity: Optional[str]
    ProjectCountyName: Optional[str]
    ProjectState: Optional[str]
    ProjectZip: Optional[str]
    CD: Optional[str]
    JobsReported: Optional[int]
    NAICSCode: Optional[str]
    Race: Optional[str]
    Ethnicity: Optional[str]
    UTILITIES_PROCEED: Optional[float]
    PAYROLL_PROCEED: Optional[float]
    MORTGAGE_INTEREST_PROCEED: Optional[float]
    RENT_PROCEED: Optional[float]
    REFINANCE_EIDL_PROCEED: Optional[float]
    HEALTH_CARE_PROCEED: Optional[float]
    DEBT_INTEREST_PROCEED: Optional[float]
    BusinessType: Optional[str]
    OriginatingLenderLocationID: Optional[str]
    OriginatingLender: Optional[str]
    OriginatingLenderCity: Optional[str]
    OriginatingLenderState: Optional[str]
    Gender: Optional[str]
    Veteran: Optional[str]
    NonProfit: Optional[str]
    ForgivenessAmount: Optional[float]
    ForgivenessDate: Optional[date]
    
    class Config:
        orm_mode = True

